name: aisleriot
description: Flutter port of GNOME Aisleriot solitaire games, including Freecell

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.0.8
  # quiver: ^3.0.1
  # tuple: ^2.0.0
  shared_preferences: ^2.0.5
  jovial_svg: ^1.0.5
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/jupiter.si
    - assets/cards/manifest.json
    - assets/cards/anglo.si
    - assets/cards/anglo_bitmap.si
    - assets/cards/bellot.si
    - assets/cards/bonded.si
    - assets/cards/dondorf.si
    - assets/cards/gnomangelo.si
    - assets/cards/gnomangelo_bitmap.si
    - assets/cards/guyenne-classic.si
    - assets/cards/ornamental.si
    - assets/cards/paris-text.si
    - assets/cards/paris.si
    - assets/cards/swiss-xvii.si
