name: aisleriot
description: Flutter port of GNOME Aisleriot solitaire games, including Freecell

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  collection: ^1.15.0
  quiver: ^3.0.1
  shared_preferences: ^2.0.5
  jovial_svg: ^1.0.5
  jovial_misc: ^0.8.4
  url_launcher: ^6.0.3
  uni_links: ^0.5.1
  uni_links_web: ^0.1.0
  # archive: ^3.1.2
  # tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/jupiter.si
    - assets/cards/manifest.json
    - assets/cards/anglo.si
    - assets/cards/anglo_bitmap.si
    - assets/cards/bellot.si
    - assets/cards/bonded.si
    - assets/cards/dondorf.si
    - assets/cards/gnomangelo.si
    - assets/cards/gnomangelo_bitmap.si
    - assets/cards/guyenne-classic.si
    - assets/cards/ornamental.si
    - assets/cards/paris-text.si
    - assets/cards/paris.si
    - assets/cards/swiss-xvii.si
